# Generated by Django 5.2.4 on 2025-09-14 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenpharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='registration',
            managers=[
            ],
        ),
    ]
