# Generated by Django 5.2.4 on 2025-09-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenpharma', '0002_product_profile_address_profile_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=20),
        ),
    ]
