# Generated by Django 4.2.7 on 2025-09-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenpharma', '0002_alter_registration_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
